export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_REQUEST = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_REQUEST = 'USER_LOGIN_FAIL'
export const USER_LOGIN_REQUEST = 'USER_LOGOUT'
